spring:
  jpa:
    database: h2
    hibernate.ddl-auto: update
    show-sql: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:~/test
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2
