spring:
  jpa:
    database: h2
    hibernate.ddl-auto: update
    show-sql: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:~/test
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2

security:
  oauth2:
    client:
      client-id: acme
      client-secret: acmesecret
      access-token-uri: http://localhost:8080/oauth/token
      user-authorization-uri: http://localhost:8080/oauth/authorize
      grant-type: password
    resource:
      user-info-uri: http://localhost:8080/me
